name: Build and Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Build Project
        env:
          NEXT_PUBLIC_BASE_PATH: ${{ secrets.BASE_PATH_STAGING }}
          NEXT_PUBLIC_API_URL: ${{ secrets.API_URL }}
          NEXT_PUBLIC_GA_ID: ''
          NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
        run: |
          npm ci
          npm run build
          npm run export
      - name: Install SSH key
        env:
          SSH_PRIVATE: ${{ secrets.SSH_PRIVATE }}
          SSH_CONFIG: ${{ secrets.SSH_CONFIG }}
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "$SSH_CONFIG" > ~/.ssh/config
          echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts
      - name: Deploy to Server
        env:
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH_STAGING }}
          REMOTE: ${{ secrets.REMOTE }}
        run: |
          chmod -R g+w out
          rsync -av out/ $REMOTE:$DEPLOY_PATH
